[versions]
agp = "8.2.0"
android-compileSdk = "34"
android-minSdk = "21"
atomicfu = "0.19.0"
coroutines = "1.6.4"
kotlin = "1.9.20" # https://github.com/JetBrains/kotlin/releases 1.9.23
ktor = "2.3.0" #https://github.com/ktorio/ktor-build-plugins/releases 2.3.13
ktlint-gradle = "14.0.1" # https://github.com/JLLeitschuh/ktlint-gradle/releases
slf4j = "1.7.36"

[libraries]
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
ktor = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }
